version: "3.8"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - node-app
      - ai



  node-app:
    container_name: finder-container
    ports:
      - 4040:4040  
    env_file:
      - ./config.env  


  ai:
    container_name: finder-ai-container
    build: 
      context: ./ai 
      dockerfile: Dockerfile    

    ports:
      - 4050:4050 

    volumes:
      - ./src/uploads/missing:/ai/src/uploads/missing

    depends_on:
      - node-app  

      